version: '3.8'

services:
  emailservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.5
    environment:
      - PORT=8080

  paymentservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.5
    environment:
      - PORT=50051

  productcatalogservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.5
    environment:
      - PORT=3550

  currencyservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.5
    environment:
      - PORT=7000

  shippingservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.5
    environment:
      - PORT=50051

  recommendationservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.5
    depends_on:
      - productcatalogservice
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550

  checkoutservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.5
    depends_on:
      - productcatalogservice
      - shippingservice
      - paymentservice
      - emailservice
      - currencyservice
      - cartservice
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070

  adservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.5
    environment:
      - PORT=9555

  cartservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.5
    depends_on:
      - redis-cart
    environment:
      - PORT=7070
      - REDIS_ADDR=redis-cart:6379

  redis-cart:
    image: redis:alpine

  frontend:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.5
    ports:
      - "8080:8080"
    depends_on:
      - productcatalogservice
      - recommendationservice
      - checkoutservice
      - adservice
      - cartservice
      - currencyservice
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - CART_SERVICE_ADDR=cartservice:7070
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
