worker_processes 1;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    location /api/users/ {
      proxy_pass http://auth:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }

    location /api/products {
      proxy_pass http://products:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }

    location /api/orders {
      proxy_pass http://orders:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }

    location /api/payments {
      proxy_pass http://payments:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }

    location / {
      proxy_pass http://client:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }
  }
}