worker_processes 1;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

<<<<<<< HEAD
location /api/users {
    proxy_pass http://auth:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
}
=======
    location /api/users/ {
      proxy_pass http://auth:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }
>>>>>>> 97ed562ec1e519754af2bc0ab1a09f8884f4254c

    location /api/products {
      proxy_pass http://products:3000;
      proxy_set_header Host $host;
<<<<<<< HEAD
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
=======
>>>>>>> 97ed562ec1e519754af2bc0ab1a09f8884f4254c
      proxy_redirect off;
    }

    location /api/orders {
      proxy_pass http://orders:3000;
      proxy_set_header Host $host;
<<<<<<< HEAD
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
=======
>>>>>>> 97ed562ec1e519754af2bc0ab1a09f8884f4254c
      proxy_redirect off;
    }

    location /api/payments {
      proxy_pass http://payments:3000;
      proxy_set_header Host $host;
<<<<<<< HEAD
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
=======
>>>>>>> 97ed562ec1e519754af2bc0ab1a09f8884f4254c
      proxy_redirect off;
    }

    location / {
      proxy_pass http://client:3000;
      proxy_set_header Host $host;
<<<<<<< HEAD
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
=======
>>>>>>> 97ed562ec1e519754af2bc0ab1a09f8884f4254c
      proxy_redirect off;
    }
  }
}