apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_KEY: anysecretkey

---

apiVersion: v1
kind: Secret
metadata:
  name: expiration-secret
type: Opaque
stringData:
  NATS_CLIENT_ID: expiration
  NATS_URL: nats://nats-srv:4222
  NATS_CLUSTER_ID: ticketing
  REDIS_HOST: redis-srv