  name: Deploy react
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
# I have added the secrets on github repo
      - run: docker build xxhjshamxx/multi-client ./microservices/client
      - run: docker build xxhjshamxx/multi-nginx ./microservices/nginx
      - run: docker build xxhjshamxx/multi-nginx ./microservices/server
      - run: docker build xxhjshamxx/multi-worker ./microservices/worker
      
      - run: docker push xxhjshamxx/multi-client
      - run: docker push xxhjshamxx/multi-nginx
      - run: docker push xxhjshamxx/multi-server
      - run: docker push xxhjshamxx/multi-worker

